version: '3.7'

services:
  web:
    build:
      context: .
    image: lsm12345/projectadminpage:latest
    volumes:
      - .:/app
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_AWS_THUMBNAIL_BUCKET_NAME=${AWS_THUMBNAIL_BUCKET_NAME}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_HOST=mariadb
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mariadb
    restart: always  # 컨테이너 자동 재시작 설정

  nginx:
    build: ./nginx
    ports:
      - "8888:80"
    depends_on:
      - web
    volumes:
      - .:/app

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mariadb_data:
